const seedProducts=[
 {id:1,name:'Alho roxo nacional',category:'Alhos',unit:'kg',price:32.9,stock:18.4,emoji:'🧄'},
 {id:2,name:'Alho descascado',category:'Alhos',unit:'kg',price:44.9,stock:7.8,emoji:'🧄'},
 {id:3,name:'Páprica defumada',category:'Temperos',unit:'kg',price:69.9,stock:4.2,emoji:'🌶️'},
 {id:4,name:'Cúrcuma em pó',category:'Temperos',unit:'kg',price:38.5,stock:6.7,emoji:'🟡'},
 {id:5,name:'Orégano selecionado',category:'Ervas',unit:'kg',price:54.9,stock:3.1,emoji:'🌿'},
 {id:6,name:'Pimenta-do-reino',category:'Pimentas',unit:'kg',price:78.9,stock:5.5,emoji:'⚫'},
 {id:7,name:'Chimichurri',category:'Temperos',unit:'kg',price:42.9,stock:8.3,emoji:'🌱'},
 {id:8,name:'Canela em pau',category:'Condimentos',unit:'kg',price:49.9,stock:2.2,emoji:'🪵'},
 {id:9,name:'Sal rosa do Himalaia',category:'Condimentos',unit:'kg',price:24.9,stock:12.6,emoji:'🧂'},
 {id:10,name:'Molho de pimenta',category:'Pimentas',unit:'un',price:18.9,stock:14,emoji:'🌶️'},
 {id:11,name:'Alecrim desidratado',category:'Ervas',unit:'kg',price:46.9,stock:1.4,emoji:'🌿'},
 {id:12,name:'Noz-moscada inteira',category:'Condimentos',unit:'un',price:4.5,stock:38,emoji:'🟤'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$$('.brand-mark').forEach(mark=>{mark.classList.add('has-logo');mark.innerHTML='<img src="logo-emporio-lourenco.jpeg" alt="Logo Empório Lourenço">'});
const reportLogo=document.createElement('img');reportLogo.src='logo-emporio-lourenco.jpeg';reportLogo.alt='Logo Empório Lourenço';reportLogo.className='report-logo';$('.report-actions>div').prepend(reportLogo);
$('.label-brand').innerHTML='<img src="logo-emporio-lourenco.jpeg" alt="Logo Empório Lourenço"><span>EMPÓRIO LOURENÇO</span>';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const db=window.supabase.createClient('https://bauoppsrqshoyvoxhlkr.supabase.co','sb_publishable_E6Y3CLxuDLjHsaq8Xsf6Lw_910MScL5');
let cloudReady=false,realtimeChannel=null;
let products=JSON.parse(localStorage.getItem('emporio_products')||'null')||seedProducts;
let sales=JSON.parse(localStorage.getItem('emporio_sales')||'[]');
let cart=[], category='Todos', discount=0, selectedProduct=null, selectedSale=null;
const save=()=>{localStorage.setItem('emporio_products',JSON.stringify(products));localStorage.setItem('emporio_sales',JSON.stringify(sales))};
async function loadCloudData(){const [{data:p,error:pe},{data:s,error:se}]=await Promise.all([db.from('products').select('*').order('name'),db.from('sales').select('*,sale_items(*)').order('created_at',{ascending:false})]);if(pe||se)throw pe||se;products=p.map(x=>({...x,price:+x.price,stock:+x.stock}));sales=s.map(x=>({id:x.id,date:x.created_at,items:x.sale_items.map(i=>({...i,qty:+i.qty,price:+i.price})),subtotal:+x.subtotal,discount:+x.discount,total:+x.total,payment:x.payment,status:x.status,cancelReason:x.cancel_reason,cancelledAt:x.cancelled_at}));cloudReady=true;renderAll()}
function startRealtime(){if(realtimeChannel)return;realtimeChannel=db.channel('pdv-live').on('postgres_changes',{event:'*',schema:'public',table:'products'},()=>loadCloudData()).on('postgres_changes',{event:'*',schema:'public',table:'sales'},()=>loadCloudData()).subscribe()}
async function enterSystem(session){if(!session)return;$('#loginModal').classList.remove('open');try{await loadCloudData();startRealtime();toast('Dados compartilhados conectados.')}catch(e){$('#loginStatus').textContent='Banco não configurado: '+e.message;$('#loginModal').classList.add('open')}}
const today=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date());
$('#dateLabel').textContent=today.charAt(0).toUpperCase()+today.slice(1);
$('#saleNumber').textContent=`Venda #${String(sales.length+1).padStart(4,'0')}`;

function renderCategories(){const cats=['Todos',...new Set(products.map(p=>p.category))];$('#categories').innerHTML=cats.map(c=>`<button class="category-btn ${c===category?'active':''}" data-category="${c}">${c}</button>`).join('');$$('.category-btn').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderCategories();renderProducts()})}
function renderProducts(){const q=$('#searchInput').value.toLowerCase();const list=products.filter(p=>(category==='Todos'||p.category===category)&&p.name.toLowerCase().includes(q));$('#productCount').textContent=`${list.length} itens disponíveis`;$('#productGrid').innerHTML=list.map(p=>`<button class="product-card" data-id="${p.id}"><div class="product-image"><span>${p.emoji||'🌿'}</span><span class="stock-badge ${p.stock<2?'low':''}">${p.stock.toLocaleString('pt-BR')} ${p.unit}</span></div><h3>${p.name}</h3><p>${p.category} · por ${p.unit}</p><strong>${money(p.price)} <small>/ ${p.unit}</small></strong></button>`).join('')||'<p>Nenhum produto encontrado.</p>';$$('.product-card').forEach(b=>b.onclick=()=>selectProduct(+b.dataset.id))}
function selectProduct(id){const p=products.find(x=>x.id===id);if(!p||p.stock<=0)return toast('Produto sem estoque.');if(p.unit==='kg'){selectedProduct=p;$('#weightTitle').textContent=p.name;$('#weightPrice').textContent=`${money(p.price)} por kg`;$('#weightInput').value='0.10';updateWeightTotal();openModal('weightModal')}else addToCart(p,1)}
function openCart(){document.body.classList.add('cart-open')}function closeCart(){document.body.classList.remove('cart-open')}
function addToCart(p,qty){const existing=cart.find(i=>i.id===p.id);if(existing)existing.qty=Math.min(existing.qty+qty,p.stock);else cart.push({...p,qty:Math.min(qty,p.stock)});renderCart();openCart();toast(`${p.name} adicionado.`)}
function totals(){const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0);return{subtotal,total:Math.max(0,subtotal-discount)}}
function renderCart(){const {subtotal,total}=totals();$('#emptyCart').style.display=cart.length?'none':'flex';$('#cartItems').innerHTML=cart.map(i=>`<div class="cart-item"><div class="cart-thumb">${i.emoji}</div><div class="cart-info"><strong>${i.name}</strong><small>${money(i.price)} / ${i.unit}</small><div class="qty-controls"><button data-act="minus" data-id="${i.id}">−</button><span>${i.qty.toLocaleString('pt-BR',{maximumFractionDigits:3})} ${i.unit}</span><button data-act="plus" data-id="${i.id}">＋</button></div></div><div class="cart-price"><strong>${money(i.price*i.qty)}</strong><button class="remove-btn" data-act="remove" data-id="${i.id}">×</button></div></div>`).join('');$('#subtotal').textContent=money(subtotal);$('#total').textContent=$('#checkoutTotal').textContent=money(total);$('#discountValue').textContent=discount?`− ${money(discount)}`:'—';$('#checkoutBtn').disabled=!cart.length;$$('[data-act]').forEach(b=>b.onclick=()=>changeItem(+b.dataset.id,b.dataset.act))}
function changeItem(id,act){const i=cart.find(x=>x.id===id);if(act==='remove'){cart=cart.filter(x=>x.id!==id)}else{const step=i.unit==='kg'?.1:1;i.qty=act==='plus'?Math.min(i.qty+step,i.stock):i.qty-step;if(i.qty<=0)cart=cart.filter(x=>x.id!==id)}renderCart()}
function openModal(id){$('#'+id).classList.add('open')}
function closeModals(){$$('.modal-backdrop').forEach(m=>m.classList.remove('open'))}
function updateWeightTotal(){$('#weightTotal').textContent=money((+$ ('#weightInput').value||0)*selectedProduct.price)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

$('#searchInput').oninput=renderProducts;$('#clearCart').onclick=()=>{cart=[];discount=0;renderCart();closeCart()};$('#closeCart').onclick=closeCart;
$('#weightInput').oninput=updateWeightTotal;$$('.quick-weights button').forEach(b=>b.onclick=()=>{$('#weightInput').value=b.dataset.weight;updateWeightTotal()});
$('#addWeightBtn').onclick=()=>{const qty=+$ ('#weightInput').value;if(qty>0){addToCart(selectedProduct,qty);closeModals()}};
$$('.modal-close').forEach(b=>b.onclick=closeModals);$$('.modal-backdrop').forEach(m=>m.onclick=e=>{if(e.target===m&&m.id!=='loginModal')closeModals()});
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginStatus').textContent='Entrando...';const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)return $('#loginStatus').textContent=error.message;$('#loginStatus').textContent='';await enterSystem(data.session)};
$('#signupBtn').onclick=async()=>{const email=$('#loginEmail').value,password=$('#loginPassword').value;if(!email||password.length<6)return $('#loginStatus').textContent='Informe e-mail e senha com pelo menos 6 caracteres.';$('#loginStatus').textContent='Criando acesso...';const {data,error}=await db.auth.signUp({email,password});if(error)return $('#loginStatus').textContent=error.message;if(data.session)await enterSystem(data.session);else $('#loginStatus').textContent='Conta criada. Confirme o e-mail recebido e depois entre.'};
$('#discountBtn').onclick=()=>{if(!cart.length)return;const value=prompt('Informe o desconto em reais:','0');if(value!==null){discount=Math.max(0,Math.min(parseFloat(value.replace(',','.'))||0,totals().subtotal));renderCart()}};
$('#checkoutBtn').onclick=()=>{$('#paymentTotal').textContent=money(totals().total);openModal('paymentModal')};
$$('[data-payment]').forEach(b=>b.onclick=()=>b.dataset.payment==='Pix'?openTestPix():finishSale(b.dataset.payment));
function openTestPix(){const {total}=totals();const code=`PIX-TESTE|EMPORIO LOURENCO|VALOR=${total.toFixed(2)}|SEM VALIDADE FINANCEIRA`;$('#pixTotal').textContent=money(total);$('#pixCode').value=code;$('#pixQr').innerHTML='';new QRCode($('#pixQr'),{text:code,width:190,height:190,colorDark:'#24322a',colorLight:'#ffffff'});closeModals();openModal('pixModal')}
$('#copyPixBtn').onclick=async()=>{await navigator.clipboard.writeText($('#pixCode').value);toast('Código Pix de teste copiado.')};
$('#confirmPixBtn').onclick=()=>finishSale('Pix — teste');
async function finishSale(payment){const {subtotal,total}=totals();if(cloudReady){const items=cart.map(({id,qty})=>({id,qty}));const {data,error}=await db.rpc('complete_sale',{p_items:items,p_discount:discount,p_payment:payment});if(error)return toast('Venda não concluída: '+error.message);cart=[];discount=0;closeModals();closeCart();await loadCloudData();toast(`Venda #${String(data).padStart(4,'0')} concluída via ${payment}.`);return}const sale={id:sales.length?Math.max(...sales.map(s=>s.id))+1:1,date:new Date().toISOString(),items:cart.map(({id,name,qty,price,unit})=>({id,name,qty,price,unit})),subtotal,discount,total,payment,status:'completed'};sales.unshift(sale);cart.forEach(i=>{const p=products.find(x=>x.id===i.id);p.stock=Math.max(0,p.stock-i.qty)});cart=[];discount=0;save();closeModals();closeCart();renderAll();toast(`Venda #${String(sale.id).padStart(4,'0')} concluída via ${payment}.`)}
function productForm(p=null){$('#productModalTitle').textContent=p?'Editar produto':'Novo produto';$('#editId').value=p?.id||'';$('#pName').value=p?.name||'';$('#pCategory').value=p?.category||'Temperos';$('#pUnit').value=p?.unit||'kg';$('#pPrice').value=p?.price||'';$('#pStock').value=p?.stock??'';openModal('productModal')}
$('#newProductBtn').onclick=()=>productForm();$('#stockNewBtn').onclick=()=>productForm();
$('#productForm').onsubmit=async e=>{e.preventDefault();const id=+$ ('#editId').value;const data={name:$('#pName').value.trim(),category:$('#pCategory').value,unit:$('#pUnit').value,price:+$('#pPrice').value,stock:+$('#pStock').value};if(cloudReady){const payload={id:id||Date.now(),...data,emoji:(id&&products.find(p=>p.id===id)?.emoji)||(data.category==='Alhos'?'🧄':data.category==='Pimentas'?'🌶️':data.category==='Ervas'?'🌿':'🫙')};const {error}=await db.from('products').upsert(payload);if(error)return toast('Erro ao salvar: '+error.message);await loadCloudData()}else{if(id)Object.assign(products.find(p=>p.id===id),data);else products.push({id:Date.now(),...data,emoji:'🫙'});save();renderAll()}closeModals();toast('Produto salvo com sucesso.')};
function renderStock(){const total=products.length,low=products.filter(p=>p.stock>0&&p.stock<2).length,out=products.filter(p=>p.stock<=0).length;$('#stockStats').innerHTML=stat('Produtos cadastrados',total,'Catálogo ativo')+stat('Estoque baixo',low,'Abaixo de 2 kg/un')+stat('Sem estoque',out,out?'Requer reposição':'Tudo abastecido');$('#stockTable').innerHTML=products.map(p=>{const st=p.stock<=0?['Sem estoque','out']:p.stock<2?['Estoque baixo','low']:['Disponível',''];return`<tr><td><div class="table-product"><span class="table-emoji">${p.emoji}</span><strong>${p.name}</strong></div></td><td>${p.category}</td><td>${money(p.price)} / ${p.unit}</td><td>${p.stock.toLocaleString('pt-BR',{maximumFractionDigits:3})} ${p.unit}</td><td><span class="status ${st[1]}">${st[0]}</span></td><td><button class="edit-btn" data-edit="${p.id}">Editar</button></td></tr>`}).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>productForm(products.find(p=>p.id===+b.dataset.edit)))}
const stat=(label,value,note)=>`<div class="stat-card"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`;
function topProducts(){const map=new Map();sales.filter(s=>s.status!=='cancelled').forEach(s=>s.items.forEach(i=>{const r=map.get(i.product_id||i.id)||{name:i.name,qty:0,revenue:0,unit:i.unit};r.qty+=i.qty;r.revenue+=i.qty*i.price;map.set(i.product_id||i.id,r)}));return[...map.values()].sort((a,b)=>b.qty-a.qty)}
function renderReports(){if(!$('#stockReportTable'))return;$('#stockReportDate').textContent=`Atualizado em ${new Date().toLocaleString('pt-BR')}`;$('#stockReportTable').innerHTML=products.map(p=>`<tr><td><div class="table-product"><span class="table-emoji">${p.emoji}</span><strong>${p.name}</strong></div></td><td>${p.category}</td><td>${p.stock.toLocaleString('pt-BR',{maximumFractionDigits:3})} ${p.unit}</td><td>${money(p.price)} / ${p.unit}</td><td><strong>${money(p.stock*p.price)}</strong></td></tr>`).join('');const top=topProducts();$('#topProductsTable').innerHTML=top.length?top.map((p,i)=>`<tr><td><span class="rank-number">${i+1}</span></td><td><strong>${p.name}</strong></td><td>${p.qty.toLocaleString('pt-BR',{maximumFractionDigits:3})} ${p.unit}</td><td><strong>${money(p.revenue)}</strong></td></tr>`).join(''):'<tr><td colspan="4" style="text-align:center;padding:30px;color:#7c877f">Nenhuma venda válida registrada.</td></tr>'}
function downloadCsv(name,rows){const csv='\ufeff'+rows.map(r=>r.map(v=>String(v).replaceAll(';',',')).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#stockCsvBtn').onclick=()=>downloadCsv('posicao-estoque.csv',[['Produto','Categoria','Quantidade','Unidade','Preço','Valor em estoque'],...products.map(p=>[p.name,p.category,p.stock,p.unit,p.price,(p.stock*p.price).toFixed(2)])]);
$('#topCsvBtn').onclick=()=>downloadCsv('itens-mais-vendidos.csv',[['Produto','Quantidade','Unidade','Receita'],...topProducts().map(p=>[p.name,p.qty,p.unit,p.revenue.toFixed(2)])]);
$('#printReportsBtn').onclick=()=>{document.body.classList.add('print-report');window.print();document.body.classList.remove('print-report')};
function renderLabelOptions(){const sel=$('#labelProduct');if(!sel)return;const current=sel.value;sel.innerHTML=products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');if(current&&products.some(p=>String(p.id)===current))sel.value=current;updateLabel()}
function updateLabel(){const p=products.find(x=>String(x.id)===$('#labelProduct').value);if(!p)return;const qty=Math.max(0,+$('#labelQty').value||0),total=qty*p.price,size=$('#labelSize').value;$('#labelPreview').className=`label-preview size-${size}`;$('#labelName').textContent=p.name;$('#labelMeta').textContent=`${qty.toLocaleString('pt-BR',{maximumFractionDigits:3})} ${p.unit} × ${money(p.price)}`;$('#labelPrice').textContent=money(total);const exp=$('#labelExpiry').value?new Date($('#labelExpiry').value+'T12:00:00').toLocaleDateString('pt-BR'):'não informada',batch=$('#labelBatch').value||'—';$('#labelDates').innerHTML=`Emb.: ${new Date().toLocaleDateString('pt-BR')}<br>Val.: ${exp}<br>Lote: ${batch}`;const code=`PROD=${p.id}|QTD=${qty}|TOTAL=${total.toFixed(2)}`;$('#labelPreview').dataset.qr=code;$('#labelQr').innerHTML='';new QRCode($('#labelQr'),{text:code,width:55,height:55})}
['labelProduct','labelSize','labelQty','labelExpiry','labelBatch'].forEach(id=>$('#'+id).addEventListener('input',updateLabel));
$('#printLabelBtn').onclick=()=>{updateLabel();const area=document.createElement('div');area.id='labelPrintArea';const size=$('#labelSize').value,[w,h]=size.split('x');for(let i=0;i<Math.min(100,+$('#labelCopies').value||1);i++){const clone=$('#labelPreview').cloneNode(true),qr=clone.querySelector('#labelQr');clone.removeAttribute('id');qr.removeAttribute('id');qr.innerHTML='';clone.classList.add('print-label-copy');clone.style.width=w+'mm';clone.style.height=h+'mm';area.appendChild(clone);new QRCode(qr,{text:$('#labelPreview').dataset.qr,width:55,height:55})}document.body.appendChild(area);document.documentElement.style.setProperty('--label-w',w+'mm');document.documentElement.style.setProperty('--label-h',h+'mm');document.body.classList.add('print-label');window.print();document.body.classList.remove('print-label');area.remove()};
function renderSales(){const valid=sales.filter(x=>x.status!=='cancelled'),revenue=valid.reduce((s,x)=>s+x.total,0),ticket=valid.length?revenue/valid.length:0;$('#salesStats').innerHTML=stat('Vendas concluídas',valid.length,`${sales.length-valid.length} canceladas`)+stat('Faturamento',money(revenue),'Cancelamentos excluídos')+stat('Ticket médio',money(ticket),'Por venda válida');$('#salesTable').innerHTML=sales.length?sales.map(s=>`<tr><td><strong>#${String(s.id).padStart(4,'0')}</strong></td><td>${new Date(s.date).toLocaleString('pt-BR')}</td><td>${s.items.reduce((a,i)=>a+i.qty,0).toLocaleString('pt-BR',{maximumFractionDigits:2})} itens</td><td>${s.status==='cancelled'?`<span class="sale-cancelled">Cancelada</span><br><small>${s.cancelReason}</small>`:s.payment}</td><td><strong>${money(s.total)}</strong>${s.status==='cancelled'?'':`<br><button class="cancel-sale-btn" data-cancel="${s.id}">Cancelar</button>`}</td></tr>`).join(''):'<tr><td colspan="5" style="text-align:center;padding:35px;color:#7c877f">Nenhuma venda registrada ainda.</td></tr>';$$('[data-cancel]').forEach(b=>b.onclick=()=>openCancel(+b.dataset.cancel))}
function openCancel(id){selectedSale=sales.find(s=>s.id===id);$('#cancelTitle').textContent=`Venda #${String(id).padStart(4,'0')}`;$('#cancelReason').value='';openModal('cancelModal')}
$('#confirmCancelBtn').onclick=async()=>{const reason=$('#cancelReason').value.trim();if(reason.length<3)return toast('Informe o motivo do cancelamento.');if(!selectedSale||selectedSale.status==='cancelled')return;if(cloudReady){const {error}=await db.rpc('cancel_sale',{p_sale_id:selectedSale.id,p_reason:reason});if(error)return toast('Não foi possível cancelar: '+error.message);closeModals();await loadCloudData();toast(`Venda #${String(selectedSale.id).padStart(4,'0')} cancelada e estoque reposto.`);return}selectedSale.items.forEach(i=>{const p=products.find(x=>x.id===i.id);if(p)p.stock+=i.qty});selectedSale.status='cancelled';selectedSale.cancelReason=reason;selectedSale.cancelledAt=new Date().toISOString();save();closeModals();renderAll();toast(`Venda #${String(selectedSale.id).padStart(4,'0')} cancelada e estoque reposto.`)};
$('#exportBtn').onclick=()=>{if(!sales.length)return toast('Ainda não há vendas para exportar.');const rows=[['Venda','Data','Pagamento','Subtotal','Desconto','Total'],...sales.map(s=>[s.id,new Date(s.date).toLocaleString('pt-BR'),s.payment,s.subtotal,s.discount,s.total])];const csv='\ufeff'+rows.map(r=>r.join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='vendas-emporio.csv';a.click();URL.revokeObjectURL(a.href)};
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view+'View').classList.add('active');$('#pageTitle').textContent={pdv:'Frente de caixa',estoque:'Estoque',vendas:'Vendas',relatorios:'Relatórios',etiquetas:'Etiquetas'}[b.dataset.view];if(b.dataset.view!=='pdv')closeCart();if(b.dataset.view==='estoque')renderStock();if(b.dataset.view==='vendas')renderSales();if(b.dataset.view==='relatorios')renderReports();if(b.dataset.view==='etiquetas')renderLabelOptions()});
document.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();$('#searchInput').focus()}if(e.key==='F10'&&cart.length){e.preventDefault();$('#checkoutBtn').click()}if(e.key==='Escape')closeModals()});
function renderAll(){renderCategories();renderProducts();renderCart();renderStock();renderSales();renderReports();renderLabelOptions();$('#saleNumber').textContent=`Venda #${String((sales[0]?.id||0)+1).padStart(4,'0')}`}
$('.operator').onclick=async()=>{if(confirm('Deseja sair do sistema?')){await db.auth.signOut();location.reload()}};
$('#logoutBtn').onclick=async()=>{if(confirm('Deseja encerrar sua sessão?')){await db.auth.signOut();location.reload()}};
db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')$('#loginModal').classList.add('open');if(event==='SIGNED_IN'&&!cloudReady)setTimeout(()=>enterSystem(session),0)});
(async()=>{renderAll();const {data:{session}}=await db.auth.getSession();if(session)await enterSystem(session);else $('#loginModal').classList.add('open')})();
